### ISSUE TITLE
Assertion `fft_size == (nframes - 1)' failed.

### ISSUE THREAD

**Issue by amantalion** [lighttransport/nanosnap#2]
Hi, I am getting the following error ```fft.cc:162: bool nanosnap::rfft(const float*, size_t, size_t, size_t, std::vector<std::complex<float> >*, bool): Assertion `fft_size == (nframes - 1)' failed.``` when calling the `stft()` function. Do you know by any chance how I could resolve it?

on this line https://github.com/lighttransport/nanosnap/blob/371aad8390be249bc52f52669d9558d0cc0fd147/src/fft.cc#L162

**Comment by syoyo** [comment]
See the comment above.
